config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-web-api:
      branch: master
      repo: https://github.com/ARGOeu/argo-web-api.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-grey-alligator.sh
        container: qc.acc_lanky-charcoal-uakari
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-web-api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-pumpkin-fish.sh
        container: qc.doc_scanty-scarlet-grasshopper
      github.com/ARGOeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-copper-wolverine.sh
        container: qc.doc_wimpy-charcoal-discus
      github.com/ARGOeu/argo-web-api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-apricot-gibbon.sh
        container: qc.doc_queasy-sangria-chihuahua
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-web-api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-mustard-goat.sh
        container: qc.lic_baggy-pink-emu
  QC.Met:
    repos:
      github.com/ARGOeu/argo-web-api cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-beige-macaw.sh
        container: qc.met_paltry-linen-bonobo
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-web-api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-amber-sparrow.sh
        container: qc.sec_fuzzy-tangerine-flounder
      github.com/ARGOeu/argo-web-api gosec:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-azure-foxhound.sh
        container: qc.sec_smelly-harlequin-octopus
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-web-api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-viridian-javanese.sh
        container: qc.sty_stinky-pear-tiger
      github.com/ARGOeu/argo-web-api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-teal-leopard.sh
        container: qc.sty_stuffy-denim-reindeer
      github.com/ARGOeu/argo-web-api staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-amber-bee.sh
        container: qc.sty_wheezy-cerise-gharial
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-web-api pytest:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-razzmatazz-argentino.sh
        container: qc.uni_woolly-olivine-barb
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-web-api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-brown-akita.sh
        container: qc.ver_flaky-blue-meerkat
timeout: 5400
