config:
  credentials: []
  project_repos:
    github.com/ARGOeu/argo-web-api:
      branch: master
      repo: https://github.com/ARGOeu/argo-web-api.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ARGOeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-sangria-gerbil.sh
        container: qc.acc_woolly-brass-coral
  QC.Doc:
    repos:
      github.com/ARGOeu/argo-web-api find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-brown-echidna.sh
        container: qc.doc_lanky-purple-duck
      github.com/ARGOeu/argo-web-api git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-saffron-tang.sh
        container: qc.doc_boozy-silver-nightingale
      github.com/ARGOeu/argo-web-api markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-coral-antelope.sh
        container: qc.doc_seedy-cerise-tang
  QC.Lic:
    repos:
      github.com/ARGOeu/argo-web-api licensee:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-vermilion-armadillo.sh
        container: qc.lic_nerdy-bistre-vulture
  QC.Met:
    repos:
      github.com/ARGOeu/argo-web-api cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-vermilion-fousek.sh
        container: qc.met_sunny-xanthic-javanese
  QC.Sec:
    repos:
      github.com/ARGOeu/argo-web-api bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-emerald-wolfhound.sh
        container: qc.sec_wiggy-pear-civet
      github.com/ARGOeu/argo-web-api gosec:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-wisteria-weasel.sh
        container: qc.sec_tasty-vermilion-okapi
  QC.Sty:
    repos:
      github.com/ARGOeu/argo-web-api flake8:
        commands:
        - /usr/bin/env sh .sqa/script.messy-rose-russel.sh
        container: qc.sty_shaggy-seashell-mandrill
      github.com/ARGOeu/argo-web-api jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-blue-discus.sh
        container: qc.sty_randy-taupe-havanese
      github.com/ARGOeu/argo-web-api staticcheck:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-sepia-kangaroo.sh
        container: qc.sty_randy-olive-chamois
  QC.Uni:
    repos:
      github.com/ARGOeu/argo-web-api pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-burgundy-malamute.sh
        container: qc.uni_woolly-wheat-jaguar
  QC.Ver:
    repos:
      github.com/ARGOeu/argo-web-api get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-lilac-hyrax.sh
        container: qc.ver_goopy-cream-frog
timeout: 5400
